apiVersion: v2
appVersion: 22.8.8
dependencies:
- name: zookeeper
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  version: 7.0.5
description: A Helm chart for ClickHouse
icon: https://raw.githubusercontent.com/ClickHouse/ClickHouse/master/website/images/logo-400x240.png
maintainers:
- email: hello@signoz.io
  name: SigNoz
  url: https://signoz.io
- email: prashant@signoz.io
  name: prashant-shahi
  url: https://prashantshahi.dev
name: clickhouse
sources:
- https://github.com/signoz/charts/
- https://github.com/ClickHouse/ClickHouse
type: application
version: 23.8.1
